operatorid: <OPID>

listenport: <MEDLISTENPORT>
listenaddr: <MEDIP>

provisioneraddr: <PROVIP>
provisionerport: <MEDIATORPORT>

mediatorid: <MEDIDNUM>

etsitls: no

#tlscert: <TLSCERT>
#tlskey: <TLSKEY>
#tlsca: <TLSCA>

RMQenabled: false
#RMQname: <RMQNAME>
#RMQpass: <RMQPASSWORD>
#RMQSSL: false
#RMQheartbeatfreq: 30
